winget install calibre.calibre
winget install Microsoft.WindowsTerminal
winget install 7zip.7zip
winget install vim.vim
winget install VideoLAN.VLC
winget install Lexikos.AutoHotkey
winget install Rufus.Rufus
winget install Microsoft.Edge
winget install Microsoft.PowerToys
winget install GnuWin32.Grep
winget install GoLang.Go
winget install Python.Python
winget install Foxit.FoxitReader
winget install Transmission.Transmission
winget install REALiX.HWiNFO
winget install Git.Git
winget install GNU.Emacs
winget install LibreOffice.LibreOffice
winget install SourceFoundry.HackFonts